remote_theme: pages-themes/minimal@v0.2.0
title: Meme-tivism to Rethink AI's Environmental Impact
description: description template

logo: "logo2.jpg"


imagesurl: "/images/"

plugins:
- jekyll-remote-theme
